### ISSUE TITLE
which commit was 1.27b built with?

### ISSUE THREAD

**Issue by stevesan** [ioan-chera/eureka-editor#129]
hello! happy user of Eureka on mac, and hoping to contribute PRs! i'm adding a simple feature (launch with +warp at 3d view pos), but building at head, some things seem to be broken, like splitting lines in vert mode. i'm wondering if this is something i did, or if this was broken since 1.27b. if i wanted to go back, which commit should i use? some simple git history searching didn't reveal anything obvious to me, nor do i see any release tags.

**Comment by neonfuz** [comment]
Hello. First to quickly answer your question, I don't know exactly which commit but you can fetch the source from the old sourceforge: https://sourceforge.net/projects/eureka-editor/files/Eureka/1.27/

Earlier I asked if the new development was versioned, and he essentially told me that anything newer than 1.27b was unstable, and that he would start versioning from 2.0 after he finishes adding a test suite to the software to ensure a certain quality level. He said that it's not really encouraged to use the editor built from head unless you're very careful, making backups etc, because people have had the editor crash and corrupt entire maps.

**Comment by ioan-chera** [comment]
> like splitting lines in vert mode

I'd love to know how it fails. I may discover the problem myself, but please tell me if there's a clear way to make that fail.

**Comment by stevesan** [comment]
so for splitting lines, it only stops working when in FREE mode. maybe this was intentional? but it is very useful in free mode, when splitting diagonal lines off the grid. screen shot of it working in 1.27b:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/1388372/187086715-e03b33c0-f9d2-4249-8d45-530a3caba580.png">

so i'm just talking about the orange dot when your cursor is near a linedef - clicking splits the linedef at the dot.

**Comment by ioan-chera** [comment]
Bug solved.
