### ISSUE TITLE
Broken lines

### ISSUE THREAD

**Issue by runlow** [ioan-chera/eureka-editor#29]
**Expected:**
Lines on the arrow indicating your position appear like lines - ie consecutive rows of pixels of same colour that create an illusion of looking at lines.

**Actual:**
It looks as if parts of the line were "erased".

Tested on Archlinux. Built at b5f1b5087acf33

![2021-02-28-073146_544x494_scrot](https://user-images.githubusercontent.com/2176657/109411110-8e56ae00-7997-11eb-8991-9df24d5cd99c.png)

**Comment by runlow** [comment]
It looks like having *things* placed affects the lines on the grid in sector view. Is it intended to work this way?

![2021-02-28-081746_794x509_scrot](https://user-images.githubusercontent.com/2176657/109412021-b0532f00-799d-11eb-914f-844e43730a4c.png)
![2021-02-28-081758_781x514_scrot](https://user-images.githubusercontent.com/2176657/109412024-b34e1f80-799d-11eb-8d46-46c881256746.png)

**Comment by ioan-chera** [comment]
In other modes, where sprites aren't displayed, the things still show as faint grey squares with direction pins. You may not see them in those instances because they're the same colours as the flat. But yes, they get painted on top of the grid or camera arrows. Whether that's appropriate is a matter of style and UI/UX. 

I may think of fixing it, since it already made you wonder what's going on, though it's less of a bug and more of an improvement this time...

**Comment by runlow** [comment]
Good points. I didn't realise that that's what was happening. Thanks for explaining. Now it makes sense.

In part it may be on the user to learn how the UI works, nevertheless to someone who doesn't know any better it could look broken - like it did to me. Now that I understand it - it makes sense.

I don't have a suggestion at the moment for how it could work different. Whichever colour you pick - there will always be a texture in the same or similar colour.
